# Generated by Django 5.2.8 on 2025-11-19 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_refreshtoken_revokedaccesstoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrolerule',
            options={'verbose_name': 'Правило доступа роли', 'verbose_name_plural': 'Правила доступа ролей'},
        ),
        migrations.AlterModelOptions(
            name='businesselement',
            options={'verbose_name': 'Бизнес-элемент', 'verbose_name_plural': 'Бизнес-элементы'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'verbose_name': 'Refresh токен', 'verbose_name_plural': 'Refresh токены'},
        ),
        migrations.AlterModelOptions(
            name='revokedaccesstoken',
            options={'verbose_name': 'Отозванный access токен', 'verbose_name_plural': 'Отозванные access токены'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='create',
            field=models.BooleanField(default=False, help_text='Право на создание элементов', verbose_name='Создание'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='delete',
            field=models.BooleanField(default=False, help_text='Право на удаление собственных элементов', verbose_name='Удаление'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='delete_all',
            field=models.BooleanField(default=False, help_text='Право на удаление всех элементов', verbose_name='Удаление всех'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='element',
            field=models.ForeignKey(help_text='Бизнес-элемент, к которому применяются права доступа', on_delete=django.db.models.deletion.CASCADE, to='users.businesselement', verbose_name='Бизнес-элемент'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='read',
            field=models.BooleanField(default=False, help_text='Право на чтение собственных элементов', verbose_name='Чтение'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='read_all',
            field=models.BooleanField(default=False, help_text='Право на чтение всех элементов', verbose_name='Чтение всех'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='role',
            field=models.ForeignKey(help_text='Роль, для которой устанавливаются права доступа', on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='update',
            field=models.BooleanField(default=False, help_text='Право на обновление собственных элементов', verbose_name='Обновление'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='update_all',
            field=models.BooleanField(default=False, help_text='Право на обновление всех элементов', verbose_name='Обновление всех'),
        ),
        migrations.AlterField(
            model_name='businesselement',
            name='code',
            field=models.SlugField(help_text='Уникальный код бизнес-элемента (slug)', max_length=64, unique=True, verbose_name='Код элемента'),
        ),
        migrations.AlterField(
            model_name='businesselement',
            name='name',
            field=models.CharField(help_text='Название бизнес-элемента', max_length=128, verbose_name='Название элемента'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(help_text='Пользователь, которому принадлежит элемент', on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='Название элемента', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания токена', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='expires_at',
            field=models.DateTimeField(help_text='Дата и время истечения срока действия токена', verbose_name='Дата истечения'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='jti',
            field=models.CharField(help_text='Уникальный идентификатор JWT токена (JTI)', max_length=36, unique=True, verbose_name='JWT ID'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='replaced_by',
            field=models.CharField(blank=True, help_text='JTI токена, который заменил данный токен при обновлении', max_length=36, null=True, verbose_name='Заменен на'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='revoked',
            field=models.BooleanField(default=False, help_text='Флаг, указывающий, был ли токен отозван', verbose_name='Отозван'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, которому принадлежит токен', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='revokedaccesstoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи об отозванном токене', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='revokedaccesstoken',
            name='expires_at',
            field=models.DateTimeField(help_text='Дата и время истечения срока действия токена', verbose_name='Дата истечения'),
        ),
        migrations.AlterField(
            model_name='revokedaccesstoken',
            name='jti',
            field=models.CharField(help_text='Уникальный идентификатор JWT токена (JTI)', max_length=36, unique=True, verbose_name='JWT ID'),
        ),
        migrations.AlterField(
            model_name='revokedaccesstoken',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, которому принадлежал токен', on_delete=django.db.models.deletion.CASCADE, related_name='revoked_access_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Уникальное название роли пользователя в системе', max_length=64, unique=True, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email пользователя для входа в систему', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор пользователя в формате UUID', primary_key=True, serialize=False, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Отчество пользователя (необязательно)', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Роли пользователя для управления доступом', to='users.role', verbose_name='Роли'),
        ),
    ]
